#!/bin/bash

#SBATCH --nodes=1

#SBATCH --time=23:00:00

#SBATCH --job-name='IM_Epinions_TBG'

#SBATCH --partition=short

#SBATCH --constraint=broadwell

#SBATCH --output=slurm_logs/IM_epinions_TBG_part_%j.out

#SBATCH --error=slurm_logs/IM_epinions_TBG_part_%j.err

srun python main.py --problemType IM --input datasets/epinions_200_nodes_150_cascades_p_0p1_seed_42 --partitions datasets/epinions_200_nodes_150_cascades_p_0p1_seed_42_partitions --policy OnlineTBG --eta $1 --n_colors $2 --k 5 --seed $3 --T 150
