#!/bin/bash

for eta in 0.01 0.05 0.1 0.2 1 10
do
    for n_colors in 1 2 4 8
    do
        for seed in 4 8 15 16 23
        do
            sbatch test_ZKC $eta $gamma $seed
        done
    done
done