#!/bin/bash

#SBATCH --nodes=1

#SBATCH --time=23:00:00

#SBATCH --job-name='IM_ZKC_OGA'

#SBATCH --partition=short

#SBATCH --constraint=broadwell

#SBATCH --output=slurm_logs/IM_ZKC_OGA%j.out

#SBATCH --error=slurm_logs/IM_ZKC_OGA%j.err

srun python main.py --problemType IM --input datasets/ZKC_100_01_42 --policy OGA --eta $1 --k 4 --seed $2 --T 100
