#!/bin/bash

#SBATCH --nodes=1

#SBATCH --time=23:00:00

#SBATCH --job-name='IM_Epinions_OGA'

#SBATCH --partition=short

#SBATCH --constraint=broadwell

#SBATCH --output=slurm_logs/IM_epinions_OGA_part_%j.out

#SBATCH --error=slurm_logs/IM_epinions_OGA_part_%j.err

srun python main.py --problemType IM --input datasets/epinions_499_nodes_500_cascades_p_0p1_seed_42 --partitions datasets/epinions_499_nodes_500_cascades_p_0p1_seed_42_partitions --policy OGA --eta $1 --gamma $2 --k 5 --seed $3 --T 500
